---
# Ansible inventory file in YAML format
# https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
    hyperv:
      hosts:
        a0.local: {}
        a1.local: {}
        a2.local: {}
    subnet:
      hosts:
        10.0.100.249:
          comment: "r249 - RKE2"
        10.10.10.100:
          comment: "Tutorial"
        10.0.100.252:
      vars:
        comment: "r252 - Docker CE + Python 3"
        # Connection
        ansible_host: 10.0.100.252
        ansible_user: gitops
        ansible_port: 2222
        ansible_connection: conn type, such as ssh (default) or local.
        ansible_shell_type: The shell type to use (e.g., bash, sh).
        ansible_shell_executable: Path to the shell binary
        # SSH
        ansible_ssh_user: u1
        ansible_ssh_private_key_file: /home/gitops/.ssh/id_rsa
        ansible_ssh_pass: SSH password (insecure practice).
        ansible_ssh_common_args: Additional SSH args.
        ansible_ssh_extra_args: '-o ControlMaster=no -i ~/.ssh/vm_common'
        # Privilege-escalation
        ansible_become: true
        ansible_become_user: root
        # OS and Package Management
        ansible_distribution: Ubuntu
        ansible_pkg_mgr: apt
        ansible_python_interpreter: /usr/bin/python3
        # Host-specific
        app_version: "1.2.3"
        db_host: "10.0.100.252"
        # Environment
        environment:
          ENV_VAR_NAME: "value"
    target:
      hosts:
        a0.local: {}
